export const ADD_TASK = "ADD_TASK";
export const UPDATE_TASK_TITLE = "UPDATE_TASK_TITLE";
export const UPDATE_TASK_DESCRIPTION = "UPDATE_TASK_DESCRIPTION";
export const UPDATE_COMPLETED_STATE = "UPDATE_COMPLETED_STATE";
export const FILTER_TASKS = "FILTER_TASKS";